apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-dns-operator
  template:
    metadata:
      labels:
        name: cluster-dns-operator
    spec:
      serviceAccountName: cluster-dns-operator
      # The operator can't rely on cluster DNS to contact the apiserver, so use
      # host networking and talk to the apiserver over loopback.
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Always
      containers:
      - name: cluster-dns-operator
        image: openshift/origin-cluster-dns-operator:latest
        command:
        - cluster-dns-operator
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: 127.0.0.1
        - name: KUBERNETES_SERVICE_PORT
          value: 8443
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "cluster-dns-operator"
