// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package router generated by go-bindata.// sources:
// testdata/coreDNS-pod.yaml
// testdata/egressfirewall-multiDomain.yaml
// testdata/egressfirewall-wildcard.yaml
// testdata/test-client-pod.yaml
// testdata/testpod-60350.yaml
// testdata/testpod-60492.yaml
// testdata/web-server-v4v6rc.yaml
package router

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _corednsPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  labels:
    name: test-coredns
  name: test-coredns
spec:
  securityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    command:
    - coredns
    image: replaced-at-runtime
    imagePullPolicy: IfNotPresent
    name: coredns
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: test-coredns-cm
    name: config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-coredns-cm
data:
  Corefile: |
    .:53 {
        bufsize 512
        errors
        log . {
            class error
        }
        health {
            lameduck 20s
        }
        ready
        template ANY MX {
            rcode NXDOMAIN
        }
        hosts {
            192.168.11.241     www.myocp-test.com
            2000::abcd     myocp-testv6.com
        }
        prometheus 127.0.0.1:9153
        forward . 8.8.8.8 {
            policy random
        }
        cache 900 {
            denial 9984 30
        }
        reload
    }
`)

func corednsPodYamlBytes() ([]byte, error) {
	return _corednsPodYaml, nil
}

func corednsPodYaml() (*asset, error) {
	bytes, err := corednsPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "coreDNS-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _egressfirewallMultidomainYaml = []byte(`kind: EgressFirewall
apiVersion: k8s.ovn.org/v1
metadata:
  name: default
spec:
  egress:
  - type: Allow
    to:
      dnsName: registry-1.docker.io
  - type: Allow
    to:
      dnsName: www.facebook.com
    ports:
      - protocol: TCP
        port: 443
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
  - type: Deny
    to:
      cidrSelector: ::/0
`)

func egressfirewallMultidomainYamlBytes() ([]byte, error) {
	return _egressfirewallMultidomainYaml, nil
}

func egressfirewallMultidomainYaml() (*asset, error) {
	bytes, err := egressfirewallMultidomainYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "egressfirewall-multiDomain.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _egressfirewallWildcardYaml = []byte(`kind: EgressFirewall
apiVersion: k8s.ovn.org/v1
metadata:
  name: default
spec:
  egress:
  - type: Allow
    to:
      dnsName: "*.google.com"
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
  - type: Deny
    to:
      cidrSelector: ::/0
`)

func egressfirewallWildcardYamlBytes() ([]byte, error) {
	return _egressfirewallWildcardYaml, nil
}

func egressfirewallWildcardYaml() (*asset, error) {
	bytes, err := egressfirewallWildcardYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "egressfirewall-wildcard.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _testClientPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-pod
  name: hello-pod
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
    name: hello-pod
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    ports:
    - containerPort: 8080
    - containerPort: 8443
`)

func testClientPodYamlBytes() ([]byte, error) {
	return _testClientPodYaml, nil
}

func testClientPodYaml() (*asset, error) {
	bytes, err := testClientPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-client-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _testpod60350Yaml = []byte(`apiVersion: v1
kind: Pod 
metadata:
  name: testpod-60350
  labels:
    app: testpod-60350
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: testpod-60350
    image: quay.io/openshifttest/busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    readinessProbe:
      exec:
        command: ['sh', '-c', 'true']
      initialDelaySeconds: 1
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ['sh', '-c', 'true']
      initialDelaySeconds: 5
      periodSeconds: 10
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  dnsPolicy: ClusterFirst
  dnsConfig:
     searches: [8th.com, 9th.com, 10th.com, 11th.com, 12th.com, 13th.com, 14th.com, 15th.com, 16th.com, 17th.com, 18th.com, 19th.com, 20th.com, 21th.com, 22th.com, 23th.com, 24th.com, 25th.com, 26th.com, 27th.com, 28th.com, 29th.com, 30th.com, 31th.com, 32th.com]
`)

func testpod60350YamlBytes() ([]byte, error) {
	return _testpod60350Yaml, nil
}

func testpod60350Yaml() (*asset, error) {
	bytes, err := testpod60350YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "testpod-60350.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _testpod60492Yaml = []byte(`apiVersion: v1
kind: Pod 
metadata:
  name: testpod-60492
  labels:
    app: testpod-60492
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: testpod-60492
    image: quay.io/openshifttest/busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    readinessProbe:
      exec:
        command: ['sh', '-c', 'true']
      initialDelaySeconds: 1
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ['sh', '-c', 'true']
      initialDelaySeconds: 5
      periodSeconds: 10
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  dnsPolicy: ClusterFirst
  dnsConfig:
     searches: [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd]

`)

func testpod60492YamlBytes() ([]byte, error) {
	return _testpod60492Yaml, nil
}

func testpod60492Yaml() (*asset, error) {
	bytes, err := testpod60492YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "testpod-60492.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _webServerV4v6rcYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: web-server-v4v6rc
    name: web-server-v4v6rc
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: web-server-v4v6rc
    template:
      metadata:
        labels:
          name: web-server-v4v6rc
      spec:
        automountServiceAccountToken: false
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
          name: nginx
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-securev4v6
    name: service-securev4v6
  spec:
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: https
      port: 27443
      protocol: TCP
      targetPort: 8443
    selector:
      name: web-server-v4v6rc
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-unsecurev4v6
    name: service-unsecurev4v6
  spec:
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: web-server-v4v6rc
`)

func webServerV4v6rcYamlBytes() ([]byte, error) {
	return _webServerV4v6rcYaml, nil
}

func webServerV4v6rcYaml() (*asset, error) {
	bytes, err := webServerV4v6rcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "web-server-v4v6rc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"coreDNS-pod.yaml":                corednsPodYaml,
	"egressfirewall-multiDomain.yaml": egressfirewallMultidomainYaml,
	"egressfirewall-wildcard.yaml":    egressfirewallWildcardYaml,
	"test-client-pod.yaml":            testClientPodYaml,
	"testpod-60350.yaml":              testpod60350Yaml,
	"testpod-60492.yaml":              testpod60492Yaml,
	"web-server-v4v6rc.yaml":          webServerV4v6rcYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"coreDNS-pod.yaml":                {corednsPodYaml, map[string]*bintree{}},
	"egressfirewall-multiDomain.yaml": {egressfirewallMultidomainYaml, map[string]*bintree{}},
	"egressfirewall-wildcard.yaml":    {egressfirewallWildcardYaml, map[string]*bintree{}},
	"test-client-pod.yaml":            {testClientPodYaml, map[string]*bintree{}},
	"testpod-60350.yaml":              {testpod60350Yaml, map[string]*bintree{}},
	"testpod-60492.yaml":              {testpod60492Yaml, map[string]*bintree{}},
	"web-server-v4v6rc.yaml":          {webServerV4v6rcYaml, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
